### ISSUE TITLE
カラム削除

### ISSUE THREAD

**Issue by noots-val** [noots-val/shindan_dev#25]
CHOICE.CHOICE_NUMBERは不要なので、削除する

**Comment by noots-val** [comment]
urlで指定していた画像列もImageFieldを使用するようにする

**Comment by yudaw** [comment]
CHOICE.CHOICE_NUMBERカラムが削除されていること 
削除されています
・画像のURLを格納するカラムが漏れなくImageFieldになっていること 
ImageFieldになっています
・上記で修正したカラムの情報のうち、カラム名が変更・削除されたものに関してadmin.pyでの記述も変更されていること
adminに反映されています
